# https://taskfile.dev
# cspell:ignore writerside,taskfile,helpbuilderinspect,xvfb

version: '3'

vars:
  WRITERSIDE_PRODUCT: Writerside/jsdos

tasks:
  default:
    cmds:
      - task: build

  build:
    vars:
      DOCKER_SOURCES_PATH: /opt/sources
      BUILD_COMMAND: >-
        export DISPLAY=:99 &&
        Xvfb :99 &
        /opt/builder/bin/idea.sh helpbuilderinspect
        --source-dir "{{ toSlash .DOCKER_SOURCES_PATH }}"
        --runner other
        --output-dir "{{ joinPath .DOCKER_SOURCES_PATH "output" | toSlash }}"
        --product "{{ .WRITERSIDE_PRODUCT }}"
    cmds:
      - cmd: >-
          docker run --rm
          -v "{{ .TASKFILE_DIR }}":"{{ toSlash .DOCKER_SOURCES_PATH }}"
          registry.jetbrains.team/p/writerside/builder/writerside-builder:241.16003
          /bin/bash -c '{{ .BUILD_COMMAND }}'

